---
name: GCR Garabage Collection

on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Setting up gloud access'
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '270.0.0'
          service_account_email: ${{ secrets.DEPLOY_SA_EMAIL }}
          service_account_key: ${{ secrets.DEPLOY_SA_CREDENTIALS }}
      - name: Setup java
          uses: actions/setup-java@v1
          with:
            java-version: 11
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build
        run: mvn -B -ntp clean verify

      - name: Run
        run: >-
          java -jar target/gcr-garbage-collect-*.jar
          --dry-run=false
          --gcloud.container.repository=eu.gcr.io/fintegra-platform-272213
          --gcloud.container.delete.before-month=1
